# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Lenovo\Downloads\ModificaProdotto.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ModificaPrincipaleProdotto(object):

    def setupUi(self, Frame, prodotto):
        self.prodottoTrovato = prodotto
        Frame.setObjectName("Frame")
        Frame.resize(437, 362)
        Frame.setStyleSheet("QFrame{\n"
                            "background-color: rgb(255, 255, 255);\n"
                            "}")
        Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame = Frame
        self.label_4 = QtWidgets.QLabel(Frame)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 421, 31))
        self.label_4.setStyleSheet("QLabel{\n"
                                   "font-family: impact, sans-serif;\n"
                                   "font-size:30px;\n"
                                   "\n"
                                   "}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(Frame)
        self.line.setGeometry(QtCore.QRect(50, 50, 321, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButtonLogout = QtWidgets.QPushButton(Frame)
        self.pushButtonLogout.setGeometry(QtCore.QRect(10, 320, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLogout.setFont(font)
        self.pushButtonLogout.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonLogout.setStyleSheet("QPushButton{\n"
                                        "border: 2px solid black;\n"
                                        "border-radius: 10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "\n"
                                        "background-color: #14626c;\n"
                                        "color:white;\n"
                                        "}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images\\log.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonLogout.setIcon(icon)
        self.pushButtonLogout.setCheckable(False)
        self.pushButtonLogout.setObjectName("pushButton_5")
        self.pushButtonRicercaProdottoSuccesso = QtWidgets.QPushButton(Frame)
        self.pushButtonRicercaProdottoSuccesso.setGeometry(QtCore.QRect(160, 320, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonRicercaProdottoSuccesso.setFont(font)
        self.pushButtonRicercaProdottoSuccesso.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonRicercaProdottoSuccesso.setStyleSheet("QPushButton{\n"
                                        "border: 2px solid black;\n"
                                        "border-radius: 10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "\n"
                                        "background-color: #14626c;\n"
                                        "color:white;\n"
                                        "}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images\\left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRicercaProdottoSuccesso.setIcon(icon1)
        self.pushButtonRicercaProdottoSuccesso.setObjectName("pushButton_4")
        self.pushButtonModificaQuantita = QtWidgets.QPushButton(Frame)
        self.pushButtonModificaQuantita.setGeometry(QtCore.QRect(20, 110, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonModificaQuantita.setFont(font)
        self.pushButtonModificaQuantita.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonModificaQuantita.setStyleSheet("QPushButton{\n"
                                        "border: 2px solid black;\n"
                                        "border-radius: 10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "\n"
                                        "background-color: #14626c;\n"
                                        "color:white;\n"
                                        "}")
        self.pushButtonModificaQuantita.setCheckable(False)
        self.pushButtonModificaQuantita.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Frame)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 170, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
                                        "border: 2px solid black;\n"
                                        "border-radius: 10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "\n"
                                        "background-color: #14626c;\n"
                                        "color:white;\n"
                                        "}")
        self.pushButton_9.setCheckable(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Frame)
        self.pushButton_10.setGeometry(QtCore.QRect(120, 240, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
                                         "border: 2px solid black;\n"
                                         "border-radius: 10px;\n"
                                         "}\n"
                                         "QPushButton:hover{\n"
                                         "\n"
                                         "background-color: #14626c;\n"
                                         "color:white;\n"
                                         "}")
        self.pushButton_10.setCheckable(False)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButtonModificaPrezzo = QtWidgets.QPushButton(Frame)
        self.pushButtonModificaPrezzo.setGeometry(QtCore.QRect(230, 110, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonModificaPrezzo.setFont(font)
        self.pushButtonModificaPrezzo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonModificaPrezzo.setStyleSheet("QPushButton{\n"
                                         "border: 2px solid black;\n"
                                         "border-radius: 10px;\n"
                                         "}\n"
                                         "QPushButton:hover{\n"
                                         "\n"
                                         "background-color: #14626c;\n"
                                         "color:white;\n"
                                         "}")
        self.pushButtonModificaPrezzo.setCheckable(False)
        self.pushButtonModificaPrezzo.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(Frame)
        self.pushButton_13.setGeometry(QtCore.QRect(230, 170, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_13.setStyleSheet("QPushButton{\n"
                                         "border: 2px solid black;\n"
                                         "border-radius: 10px;\n"
                                         "}\n"
                                         "QPushButton:hover{\n"
                                         "\n"
                                         "background-color: #14626c;\n"
                                         "color:white;\n"
                                         "}")
        self.pushButton_13.setCheckable(False)
        self.pushButton_13.setObjectName("pushButton_13")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(10, 60, 421, 41))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("QLabel{\n"
                                 "font-family: Helvetica, sans-serif;\n"
                                 "font-weight: 400;\n"
                                 "font-size: 16px\n"
                                 "}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButtonLogout.clicked.connect(self.openLogin)
        self.pushButtonRicercaProdottoSuccesso.clicked.connect(self.openRicercaProdottoSuccesso)
        self.pushButtonModificaQuantita.clicked.connect(self.openModificaQuantitaProdotto)
        self.pushButtonModificaPrezzo.clicked.connect(self.openModificaPrezzoProdotto)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Fumetteria - Modifica Prodotto"))
        self.label_4.setText(_translate("Frame", "MODIFICA PRODOTTO"))
        self.pushButtonLogout.setText(_translate("Frame", " Logout"))
        self.pushButtonRicercaProdottoSuccesso.setText(_translate("Frame", " Indietro"))
        self.pushButtonModificaQuantita.setText(_translate("Frame", "Modifica\n"
                                                      "Quantità Prodotto"))
        self.pushButton_9.setText(_translate("Frame", "Modifica\n"
                                                      "Codice Seriale "))
        self.pushButton_10.setText(_translate("Frame", "Modifica\n"
                                                       " Offerta Prodotto"))
        self.pushButtonModificaPrezzo.setText(_translate("Frame", "Modifica \n"
                                                       "Prezzo Prodotto"))
        self.pushButton_13.setText(_translate("Frame", "Elimina \n"
                                                       " Prodotto"))
        self.label.setText(_translate("Frame", "Seleziona una delle opzioni per modificare il prodotto "))

    # metodo che riporta alla pagina del login
    def openLogin(self):
        from Grafica.GestioneLogin.LoginAmministratore import LoginAmministratore
        self.login = QtWidgets.QFrame()
        self.ui = LoginAmministratore()
        self.ui.setupUi(self.login)
        self.login.show()
        self.frame.close()

    # metodo che riporta l'utente all'interno della schermata RicercaProdottoSuccesso
    # dopo aver cliccato indietro
    def openRicercaProdottoSuccesso(self):
        from Grafica.GestioneMagazzino.RicercaProdottoSuccesso import RicercaProdottoSuccesso
        self.modificaQuantitaProdotto = QtWidgets.QFrame()
        self.ui = RicercaProdottoSuccesso()
        self.ui.setupUi(self.modificaQuantitaProdotto, self.prodottoTrovato)
        self.modificaQuantitaProdotto.show()
        self.frame.close()

    # metodo permette all'utente di modificare la quantità dei pezzi
    # del prodotto presenti nel magazzino
    def openModificaQuantitaProdotto(self):
        from Grafica.GestioneMagazzino.ModificaProdotto.ModificaQuantitaProdotto import ModificaQuantitaProdotto
        self.modificaQuantitaProdotto = QtWidgets.QFrame()
        self.ui = ModificaQuantitaProdotto()
        self.ui.setupUi(self.modificaQuantitaProdotto, self.prodottoTrovato)
        self.modificaQuantitaProdotto.show()
        self.frame.close()

    # metodo permette all'utente di modificare il prezzo base
    # del prodotto presenti nel magazzino
    def openModificaPrezzoProdotto(self):
        from Grafica.GestioneMagazzino.ModificaProdotto.ModificaPrezzoProdotto import ModificaPrezzoProdotto
        self.modificaPrezzoProdotto = QtWidgets.QFrame()
        self.ui = ModificaPrezzoProdotto()
        self.ui.setupUi(self.modificaPrezzoProdotto, self.prodottoTrovato)
        self.modificaPrezzoProdotto.show()
        self.frame.close()



